### ISSUE TITLE
Change apline

### ISSUE THREAD

**Issue by T-Dynamos** [xeffyr/android-vshell#10]
Please change apline to debain based linux because most of the users find difficult to use apline and debain is easy i also know limitations
But please replace and apline has many bugs
Add option of new terminal please its kind a useful :)

**Comment by Yonle** [comment]
Change ISO file and enjoy 10 TB recommended package from apt repo

**Comment by leapofazzam123** [comment]
no

**Comment by xeffyr** [comment]
Nope, this never will happen.

Why:
* Because I need specifically Alpine Linux.
* Alpine Linux is distributed in 40-50 MB ISO file. *Now you're telling me to add 300-500 MB Debian img?*
* Alpine Linux is in general faster in QEMU than **any** of GNU libc based distributions, especially using systemd. They also have speed issues in QEMU with packages like `man-db` - takes hours to regenerate manpage database.

> But please replace and apline has many bugs

Many bugs? Do you have many facts about these bugs? Have you tried reporting at least few of them to Alpine Linux developers?

Most of these "bugs" are usually called "user errors" and "lack of knowledge". Distribution by itself is very stable, unless you're going to install GUI or something like. Don't forget that Alpine is not for desktops, but for primarily intended for use on servers, routers or containers.

> Add option of new terminal please its kind a useful

New design makes this impossible. Terminal is bound to QEMU instance. I would not add any middleware (socket client) like https://github.com/xeffyr/alpine-term does, neither will do heavy modifications to QEMU.

To have multiple terminals you have `tmux`, `openssh` (need external application client), etc.

Also check https://github.com/xeffyr/android-vshell#limitations.

**Comment by T-Dynamos** [comment]
> Change ISO file and enjoy 10 TB recommended package from apt repo

How to change

**Comment by Yonle** [comment]
> > Change ISO file and enjoy 10 TB recommended package from apt repo
> 
> How to change

Ask yourself.
