### ISSUE TITLE
[Feature]: Zsh preinstalled

### ISSUE THREAD

**Issue by T-Dynamos** [xeffyr/android-vshell#16]
### Feature description

Why zsh is preinstalled instead of bash

### Design limits acknowledgement

- [X] I have read and understand [LIMITATIONS.md](https://github.com/xeffyr/android-vshell/blob/master/LIMITATIONS.md)

**Comment by Yonle** [comment]
This is **NOT** feature request. Also there's a good reason why zsh is preinstalled:

1. `ash` is almost like what `dash` or `sh` does. 
2. `zsh` is almost same as what `bash` does. 
And some reason that i can't explain

**Comment by xeffyr** [comment]
Because I need it. Don't forget that vShell has been created specifically for my needs and used defaults as well as app design & VM configuration may not be suitable for everyone.

Also Zsh unlike Bash has a pre-exec hook which allows to exec some code before executing the command specified on prompt. That allows to normalize console (hopefully you know the difference between normal terminal and serial console and why `resize` execution is needed) size before executing program. Bash doesn't have such feature, but the closest one can be implemented through `$PROMPT_COMMAND`, but it's issue is that it is being executed during prompt initialization (after command has been executed or on shell startup) and not exactly before.
