### ISSUE TITLE
Q: any opportunity to speed-up the system start? 

### ISSUE THREAD

**Issue by 4ntoine** [xeffyr/android-vshell#4]
It's mentioned that it takes minutes to start-up the system and it depends on device performance.
On my Android device it takes about 4 minutes.

Is there any opportunity to speed-up the system start (ideally to fit into 30 seconds on low-end device)?
I've also noted it's x86_64 image is being used (if i'm not mistaken). As most of Android devices are ARM can ARM 64bit image be used instead (will it help)? Any other options (reduce running system services), anything?

**Comment by WMCB-Tech** [comment]
I think snapshots would help to save state then restore it back, just like AVD does (which saves state when closing android virtual device)

**Comment by 4ntoine** [comment]
@WMCB-Tech That could help indeed - thanks for the suggestion, appreciate it! Is it in your [fork](https://github.com/WMCB-Tech/android-vshell)?

> about changing the image to arm instead of x86, i think it is still being emulated a little complex to do

Can you please explain why is it complex? Is it conceptually supported (seems to be by qemu)

**Comment by WMCB-Tech** [comment]
> appreciate it! Is it in your fork?
Yes it's my fork

> Can you please explain why is it complex? Is it conceptually supported (seems to be by qemu)

It is supported, but they have different configurations, basically when booting ARM linux, sometimes you may need to specify kernel, initrd flags. which i'm having a hard time

you may check here
https://wiki.qemu.org/Documentation/Platforms/ARM

**Comment by xeffyr** [comment]
It is slow because emulated. There no KVM, which will require special kernel and supported device (with no ARM TrustZone).

Using ARM 64 image will be useless, since it will be on emulated hardware anyway. There no plans to change architecture of emulated CPU.

**Comment by 4ntoine** [comment]
@WMCB-Tech can't find your snapshot-related changes: https://github.com/WMCB-Tech/android-vshell/commits?author=WMCB-Tech. Can you please point?

**Comment by WMCB-Tech** [comment]
I enabled QEMU Monitor to listen to telnet port 5678, then use `savevm` and `loadvm` commands

**Comment by 4ntoine** [comment]
@WMCB-Tech You were right - unmounting `/media/host` helped. Any hint on how to load right into the snapshot (not just boot the vm)?

**Comment by WMCB-Tech** [comment]
connect to telnet again and do `loadvm <snapshot-name>`

***

P.S. this doesn't work only if you unspecified some device drives or adjusted qemu runtime arguments

**Comment by xeffyr** [comment]
@WMCB-Tech It is not necessary to enable telnet or something like to access monitor console. Just use this patch https://github.com/xeffyr/android-vshell/commit/dca0ef84c6b797e1009423a95eb3769786bd3788 (won't be included into official release).

**Comment by 4ntoine** [comment]
@WMCB-Tech is there anything better than the following:
```
    new Thread(new Runnable() {
            @Override
            public void run() {
                SystemClock.sleep(1_000); // wait for boot started (is it needed?)
                try {
                    Socket socket = new Socket(InetAddress.getLoopbackAddress(), port); // localhost
                    int len = 128;
                    byte[] buffer = new byte[len];
                    int read = socket.getInputStream().read(buffer, 0, len);
                    if (read > 0) {
                        String message = new String(buffer, 0, read);
                        Log.w("vshell", "Got an invite message: " + message);
                    } else {
                        Log.e("vshell", "No invite message");
                    }
                    try {
                        PrintWriter writer = new PrintWriter(socket.getOutputStream(), true);
                        writer.println("loadvm extracted"); // "extracted" is existing snapshot name
                        writer.flush();
                        socket.getOutputStream().flush();
                    } finally {
                        socket.close();
                    }
                } catch (IOException e) {
                    Log.e("vshell", "Failed to load a snapshot", e);
                }
            }
        }).start();
```

**Comment by xeffyr** [comment]
> is there anything better than the following:

Its QMP: https://wiki.qemu.org/Documentation/QMP. The monitor protocol specifically designed to be used by external applications.

Normal monitor console is designed only for direct interactive use.

**Comment by WMCB-Tech** [comment]
> Just use this patch dca0ef8 (won't be included into official release).

Thanks @xeffyr i think this is what i'm looking for

**Comment by 4ntoine** [comment]
@xeffyr i've found 3.1 Mb executable (x86-64) run (simple 'app --version') on one of my low-end devices (just for the testing) takes incredible 3.18 seconds. Any advice from you on how i can speed-up the execution? Probably some qemu args (to have hardware accel) or faster disk format (raw/qcow/qcow2)?

Here are the args i'm using (pretty much the same as in original source code but without operating-system.iso mounted as cdrom):

``
2021-08-12 23:22:37.231 22435-22435/app.virtshell I/virt-shell:app: initiating QEMU session with following arguments: [vShell, -L, /data/user/0/app.virtshell/files, -cpu, max, -smp, cpus=4,cores=4,threads=1,sockets=1, -device, virtio-balloon, -m, 584M, -accel, tcg,tb-size=146, -nodefaults, -drive, file=/data/user/0/app.virtshell/files/userdata.qcow2,if=none,index=2,discard=unmap,detect-zeroes=unmap,cache=writeback,id=hd0, -device, virtio-scsi-pci,id=virtio-scsi-pci0, -device, scsi-hd,bus=virtio-scsi-pci0.0,id=scsi-hd0,drive=hd0, -boot, c,menu=on, -object, rng-random,filename=/dev/urandom,id=rng0, -device, virtio-rng-pci,rng=rng0,id=virtio-rng-pci0, -netdev, user,id=vmnic0,hostfwd=tcp::45805-:22,hostfwd=tcp::41915-:80, -device, virtio-net-pci,netdev=vmnic0,id=virtio-net-pci0, -fsdev, local,security_model=none,id=fsdev0,multidevs=remap,path=/storage/self/primary, -device, virtio-9p-pci,fsdev=fsdev0,mount_tag=host_storage,id=virtio-9p-pci0, -nographic, -parallel, none, -chardev, stdio,id=serial0,mux=off,signal=off, -serial, chardev:serial0, ]
``

**Comment by xeffyr** [comment]
> Any advice from you on how i can speed-up the execution?

It is already on max possible speed level. If you need faster emulation, this application probably isn't for you. Higher performance can be achieved only either with hardware acceleration (KVM) which isn't supported or specialized emulators (something like box86).

> some qemu args (to have hardware accel)

Here is what required to have hardware acceleration:
* Device **without** ARM TrustZone or its old version or it has been disabled on bootloader level. Otherwise you'll never get hypervisor mode - tested.
* Device must be rooted to `chown 666 /dev/kvm` and set SELinux to permissive.
* QEMU must emulate same architecture as CPU of your device. *This condition isn't met with official application variant. I provide x86_64 emulation only.*

Also note that kvm support is disabled during QEMU build time. I won't enable it or even make it optional as well as any other features requiring device modifications.

> BTW is using system image + writable data faster (why did you choose that approach instead of single writable drive with system installed)?

I don't get what you are trying to say/ask there, but I have really fast disk access. Writing data at 100+ MiB/sec inside emulator on my device with UFS2.1.

Disk access has very low impact on execution speed. This depends on used software (I often seen that 60 MiB binary executes faster than 600 KiB one somehow), device battery management and of course CPU - in case of vShell (QEMU), you should care about max possible single-core performance.

The "diskless" Alpine Linux configuration has been chosen intentionally according to my usage workflow of application. Btw it doesn't reads/writes only data in your $HOME to disk by default, everything else (rootfs) is stored entirely in RAM. Disk installations are recommended only for users with low RAM, who wish to install lots of packages, be able to upgrade kernel without waiting vShell update with newer disk image or just wants to install a custom OS.

**Comment by xeffyr** [comment]
> -cpu, max, -smp, cpus=4,cores=4,threads=1,sockets=1

Just FYI: more cores won't give you more performance inside QEMU. Internally, all these cores are emulated within one QEMU thread on round-robin fashion. You potentially can get even worse performance (every core gets a fixed allowed execution time before switch).

**Comment by 4ntoine** [comment]
@xeffyr yup i noticed it with `info cpus` - they have the same thread id. Going to try 1 cpu
